# Generated by Django 4.0 on 2021-12-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetail',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
