# Generated by Django 4.0 on 2021-12-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_city_user_college_user_participation_user_total'),
        ('CA', '0002_registrationdetail_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdetail',
            name='email',
        ),
        migrations.AddField(
            model_name='registrationdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
